### ISSUE TITLE
running error

### ISSUE THREAD

**Issue by 135355** [benmoseley/FBPINNs#5]
Hello，I am trying to use your program to write a FBPINN that solves a 3D temperature field, because the problem is more complex, I use the soft-constrained loss function form in the problem class.Because used a soft constrained loss function, so def boundary_condition() is not used in the problem class.However, when commenting out FBPINN and just running PINN, the error still occurs.
I am getting an error while running the file paper_main_3D.py.,
The screenlog:
RUN: final_FBPINN_TemperatureField3D_16h_2l_30b_r_0.1w_All
P: <problems.TemperatureField3D object at 0x0000020521F32808>
SUBDOMAIN_XS: [array([0.  , 0.25, 0.5 , 0.75, 1.  ]), array([0.  , 0.25, 0.5 , 0.75, 1.  ]), array([0.  , 0.25, 0.5 , 0.75, 1.  ])]
SUBDOMAIN_WS: [array([0.025, 0.025, 0.025, 0.025, 0.025]), array([0.025, 0.025, 0.025, 0.025, 0.025]), array([0.025, 0.025, 0.025, 0.025, 0.025])]
BOUNDARY_N: (0.1,)
Y_N: (0, 1)
ACTIVE_SCHEDULER: <class 'active_schedulers.AllActiveSchedulerND'>
ACTIVE_SCHEDULER_ARGS: ()
DEVICE: 0
MODEL: <class 'models.FCN'>
N_HIDDEN: 16
N_LAYERS: 2
BATCH_SIZE: (30, 30, 30)
RANDOM: True
LRATE: 0.001
N_STEPS: 150000
SEED: 123
BATCH_SIZE_TEST: (100, 100, 10)
PLOT_LIMS: (0.4, True)
SUMMARY_FREQ: 250
TEST_FREQ: 5000
MODEL_SAVE_FREQ: 10000
SHOW_FIGURES: False
SAVE_FIGURES: False
CLEAR_OUTPUT: False
SUMMARY_OUT_DIR: results/summaries/final_FBPINN_TemperatureField3D_16h_2l_30b_r_0.1w_All/
MODEL_OUT_DIR: results/models/final_FBPINN_TemperatureField3D_16h_2l_30b_r_0.1w_All/
HOSTNAME: laptop-8t1qinad

Device: cuda:0
Main thread ID: 7240
Torch seed:  123
0 Active updated:
 [[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]
torch.Size([512, 1]) torch.Size([512, 1]) torch.Size([512, 1]) torch.Size([0, 1]) torch.Size([0, 1]) torch.Size([0, 1]) torch.Size([0, 1]) torch.Size([512, 3])
torch.Size([576, 1]) torch.Size([576, 1]) torch.Size([576, 1]) torch.Size([0, 1]) torch.Size([0, 1]) torch.Size([0, 1]) torch.Size([0, 1]) torch.Size([576, 3])
torch.Size([576, 1]) torch.Size([576, 1]) torch.Size([576, 1]) torch.Size([0, 1]) torch.Size([0, 1]) torch.Size([0, 1]) torch.Size([0, 1]) torch.Size([576, 3])
torch.Size([512, 1]) torch.Size([512, 1]) torch.Size([512, 1]) torch.Size([0, 1]) torch.Size([0, 1]) torch.Size([0, 1]) torch.Size([0, 1]) torch.Size([512, 3])
torch.Size([576, 1]) torch.Size([576, 1]) torch.Size([576, 1]) torch.Size([0, 1]) torch.Size([0, 1]) torch.Size([0, 1]) torch.Size([0, 1]) torch.Size([576, 3])
torch.Size([648, 1]) torch.Size([648, 1]) torch.Size([648, 1]) torch.Size([0, 1]) torch.Size([0, 1]) torch.Size([0, 1]) torch.Size([0, 1]) torch.Size([648, 3])
torch.Size([648, 1]) torch.Size([648, 1]) torch.Size([648, 1]) torch.Size([0, 1]) torch.Size([0, 1]) torch.Size([0, 1]) torch.Size([0, 1]) torch.Size([648, 3])
torch.Size([576, 1]) torch.Size([576, 1]) torch.Size([576, 1]) torch.Size([0, 1]) torch.Size([0, 1]) torch.Size([0, 1]) torch.Size([0, 1]) torch.Size([576, 3])
torch.Size([576, 1]) torch.Size([576, 1]) torch.Size([576, 1]) torch.Size([0, 1]) torch.Size([0, 1]) torch.Size([0, 1]) torch.Size([0, 1]) torch.Size([576, 3])
torch.Size([648, 1]) torch.Size([648, 1]) torch.Size([648, 1]) torch.Size([0, 1]) torch.Size([0, 1]) torch.Size([0, 1]) torch.Size([0, 1]) torch.Size([648, 3])
torch.Size([648, 1]) torch.Size([648, 1]) torch.Size([648, 1]) torch.Size([0, 1]) torch.Size([0, 1]) torch.Size([0, 1]) torch.Size([0, 1]) torch.Size([648, 3])
torch.Size([576, 1]) torch.Size([576, 1]) torch.Size([576, 1]) torch.Size([0, 1]) torch.Size([0, 1]) torch.Size([0, 1]) torch.Size([0, 1]) torch.Size([576, 3])
torch.Size([512, 1]) torch.Size([512, 1]) torch.Size([512, 1]) torch.Size([0, 1]) torch.Size([0, 1]) torch.Size([0, 1]) torch.Size([0, 1]) torch.Size([512, 3])
torch.Size([576, 1]) torch.Size([576, 1]) torch.Size([576, 1]) torch.Size([0, 1]) torch.Size([0, 1]) torch.Size([0, 1]) torch.Size([0, 1]) torch.Size([576, 3])
torch.Size([576, 1]) torch.Size([576, 1]) torch.Size([576, 1]) torch.Size([0, 1]) torch.Size([0, 1]) torch.Size([0, 1]) torch.Size([0, 1]) torch.Size([576, 3])
torch.Size([512, 1]) torch.Size([512, 1]) torch.Size([512, 1]) torch.Size([0, 1]) torch.Size([0, 1]) torch.Size([0, 1]) torch.Size([0, 1]) torch.Size([512, 3])
torch.Size([576, 1]) torch.Size([576, 1]) torch.Size([576, 1]) torch.Size([0, 1]) torch.Size([0, 1]) torch.Size([0, 1]) torch.Size([0, 1]) torch.Size([576, 3])
torch.Size([648, 1]) torch.Size([648, 1]) torch.Size([648, 1]) torch.Size([0, 1]) torch.Size([0, 1]) torch.Size([0, 1]) torch.Size([0, 1]) torch.Size([648, 3])
torch.Size([648, 1]) torch.Size([648, 1]) torch.Size([648, 1]) torch.Size([0, 1]) torch.Size([0, 1]) torch.Size([0, 1]) torch.Size([0, 1]) torch.Size([648, 3])
torch.Size([576, 1]) torch.Size([576, 1]) torch.Size([576, 1]) torch.Size([0, 1]) torch.Size([0, 1]) torch.Size([0, 1]) torch.Size([0, 1]) torch.Size([576, 3])
torch.Size([648, 1]) torch.Size([648, 1]) torch.Size([648, 1]) torch.Size([0, 1]) torch.Size([0, 1]) torch.Size([0, 1]) torch.Size([0, 1]) torch.Size([648, 3])
torch.Size([729, 1]) torch.Size([729, 1]) torch.Size([729, 1]) torch.Size([0, 1]) torch.Size([0, 1]) torch.Size([0, 1]) torch.Size([0, 1]) torch.Size([729, 3])
torch.Size([729, 1]) torch.Size([729, 1]) torch.Size([729, 1]) torch.Size([0, 1]) torch.Size([0, 1]) torch.Size([0, 1]) torch.Size([0, 1]) torch.Size([729, 3])
torch.Size([648, 1]) torch.Size([648, 1]) torch.Size([648, 1]) torch.Size([0, 1]) torch.Size([0, 1]) torch.Size([0, 1]) torch.Size([0, 1]) torch.Size([648, 3])
torch.Size([648, 1]) torch.Size([648, 1]) torch.Size([648, 1]) torch.Size([0, 1]) torch.Size([0, 1]) torch.Size([0, 1]) torch.Size([0, 1]) torch.Size([648, 3])
torch.Size([729, 1]) torch.Size([729, 1]) torch.Size([729, 1]) torch.Size([0, 1]) torch.Size([0, 1]) torch.Size([0, 1]) torch.Size([0, 1]) torch.Size([729, 3])
torch.Size([729, 1]) torch.Size([729, 1]) torch.Size([729, 1]) torch.Size([0, 1]) torch.Size([0, 1]) torch.Size([0, 1]) torch.Size([0, 1]) torch.Size([729, 3])
torch.Size([648, 1]) torch.Size([648, 1]) torch.Size([648, 1]) torch.Size([0, 1]) torch.Size([0, 1]) torch.Size([0, 1]) torch.Size([0, 1]) torch.Size([648, 3])
torch.Size([576, 1]) torch.Size([576, 1]) torch.Size([576, 1]) torch.Size([0, 1]) torch.Size([0, 1]) torch.Size([0, 1]) torch.Size([0, 1]) torch.Size([576, 3])
torch.Size([648, 1]) torch.Size([648, 1]) torch.Size([648, 1]) torch.Size([0, 1]) torch.Size([0, 1]) torch.Size([0, 1]) torch.Size([0, 1]) torch.Size([648, 3])
torch.Size([648, 1]) torch.Size([648, 1]) torch.Size([648, 1]) torch.Size([0, 1]) torch.Size([0, 1]) torch.Size([0, 1]) torch.Size([0, 1]) torch.Size([648, 3])
torch.Size([576, 1]) torch.Size([576, 1]) torch.Size([576, 1]) torch.Size([0, 1]) torch.Size([0, 1]) torch.Size([0, 1]) torch.Size([0, 1]) torch.Size([576, 3])
torch.Size([576, 1]) torch.Size([576, 1]) torch.Size([576, 1]) torch.Size([0, 1]) torch.Size([0, 1]) torch.Size([0, 1]) torch.Size([0, 1]) torch.Size([576, 3])
torch.Size([648, 1]) torch.Size([648, 1]) torch.Size([648, 1]) torch.Size([0, 1]) torch.Size([0, 1]) torch.Size([0, 1]) torch.Size([0, 1]) torch.Size([648, 3])
torch.Size([648, 1]) torch.Size([648, 1]) torch.Size([648, 1]) torch.Size([0, 1]) torch.Size([0, 1]) torch.Size([0, 1]) torch.Size([0, 1]) torch.Size([648, 3])
torch.Size([576, 1]) torch.Size([576, 1]) torch.Size([576, 1]) torch.Size([0, 1]) torch.Size([0, 1]) torch.Size([0, 1]) torch.Size([0, 1]) torch.Size([576, 3])
torch.Size([648, 1]) torch.Size([648, 1]) torch.Size([648, 1]) torch.Size([0, 1]) torch.Size([0, 1]) torch.Size([0, 1]) torch.Size([0, 1]) torch.Size([648, 3])
torch.Size([729, 1]) torch.Size([729, 1]) torch.Size([729, 1]) torch.Size([0, 1]) torch.Size([0, 1]) torch.Size([0, 1]) torch.Size([0, 1]) torch.Size([729, 3])
torch.Size([729, 1]) torch.Size([729, 1]) torch.Size([729, 1]) torch.Size([0, 1]) torch.Size([0, 1]) torch.Size([0, 1]) torch.Size([0, 1]) torch.Size([729, 3])
torch.Size([648, 1]) torch.Size([648, 1]) torch.Size([648, 1]) torch.Size([0, 1]) torch.Size([0, 1]) torch.Size([0, 1]) torch.Size([0, 1]) torch.Size([648, 3])
torch.Size([648, 1]) torch.Size([648, 1]) torch.Size([648, 1]) torch.Size([0, 1]) torch.Size([0, 1]) torch.Size([0, 1]) torch.Size([0, 1]) torch.Size([648, 3])
torch.Size([729, 1]) torch.Size([729, 1]) torch.Size([729, 1]) torch.Size([0, 1]) torch.Size([0, 1]) torch.Size([0, 1]) torch.Size([0, 1]) torch.Size([729, 3])
torch.Size([729, 1]) torch.Size([729, 1]) torch.Size([729, 1]) torch.Size([0, 1]) torch.Size([0, 1]) torch.Size([0, 1]) torch.Size([0, 1]) torch.Size([729, 3])
torch.Size([648, 1]) torch.Size([648, 1]) torch.Size([648, 1]) torch.Size([0, 1]) torch.Size([0, 1]) torch.Size([0, 1]) torch.Size([0, 1]) torch.Size([648, 3])
torch.Size([576, 1]) torch.Size([576, 1]) torch.Size([576, 1]) torch.Size([0, 1]) torch.Size([0, 1]) torch.Size([0, 1]) torch.Size([0, 1]) torch.Size([576, 3])
torch.Size([648, 1]) torch.Size([648, 1]) torch.Size([648, 1]) torch.Size([0, 1]) torch.Size([0, 1]) torch.Size([0, 1]) torch.Size([0, 1]) torch.Size([648, 3])
torch.Size([648, 1]) torch.Size([648, 1]) torch.Size([648, 1]) torch.Size([0, 1]) torch.Size([0, 1]) torch.Size([0, 1]) torch.Size([0, 1]) torch.Size([648, 3])
torch.Size([576, 1]) torch.Size([576, 1]) torch.Size([576, 1]) torch.Size([0, 1]) torch.Size([0, 1]) torch.Size([0, 1]) torch.Size([0, 1]) torch.Size([576, 3])
torch.Size([512, 1]) torch.Size([512, 1]) torch.Size([512, 1]) torch.Size([0, 1]) torch.Size([0, 1]) torch.Size([0, 1]) torch.Size([0, 1]) torch.Size([512, 3])
torch.Size([576, 1]) torch.Size([576, 1]) torch.Size([576, 1]) torch.Size([0, 1]) torch.Size([0, 1]) torch.Size([0, 1]) torch.Size([0, 1]) torch.Size([576, 3])
torch.Size([576, 1]) torch.Size([576, 1]) torch.Size([576, 1]) torch.Size([0, 1]) torch.Size([0, 1]) torch.Size([0, 1]) torch.Size([0, 1]) torch.Size([576, 3])
torch.Size([512, 1]) torch.Size([512, 1]) torch.Size([512, 1]) torch.Size([0, 1]) torch.Size([0, 1]) torch.Size([0, 1]) torch.Size([0, 1]) torch.Size([512, 3])
torch.Size([576, 1]) torch.Size([576, 1]) torch.Size([576, 1]) torch.Size([0, 1]) torch.Size([0, 1]) torch.Size([0, 1]) torch.Size([0, 1]) torch.Size([576, 3])
torch.Size([648, 1]) torch.Size([648, 1]) torch.Size([648, 1]) torch.Size([0, 1]) torch.Size([0, 1]) torch.Size([0, 1]) torch.Size([0, 1]) torch.Size([648, 3])
torch.Size([648, 1]) torch.Size([648, 1]) torch.Size([648, 1]) torch.Size([0, 1]) torch.Size([0, 1]) torch.Size([0, 1]) torch.Size([0, 1]) torch.Size([648, 3])
torch.Size([576, 1]) torch.Size([576, 1]) torch.Size([576, 1]) torch.Size([0, 1]) torch.Size([0, 1]) torch.Size([0, 1]) torch.Size([0, 1]) torch.Size([576, 3])
torch.Size([576, 1]) torch.Size([576, 1]) torch.Size([576, 1]) torch.Size([0, 1]) torch.Size([0, 1]) torch.Size([0, 1]) torch.Size([0, 1]) torch.Size([576, 3])
torch.Size([648, 1]) torch.Size([648, 1]) torch.Size([648, 1]) torch.Size([0, 1]) torch.Size([0, 1]) torch.Size([0, 1]) torch.Size([0, 1]) torch.Size([648, 3])
torch.Size([648, 1]) torch.Size([648, 1]) torch.Size([648, 1]) torch.Size([0, 1]) torch.Size([0, 1]) torch.Size([0, 1]) torch.Size([0, 1]) torch.Size([648, 3])
torch.Size([576, 1]) torch.Size([576, 1]) torch.Size([576, 1]) torch.Size([0, 1]) torch.Size([0, 1]) torch.Size([0, 1]) torch.Size([0, 1]) torch.Size([576, 3])
torch.Size([512, 1]) torch.Size([512, 1]) torch.Size([512, 1]) torch.Size([0, 1]) torch.Size([0, 1]) torch.Size([0, 1]) torch.Size([0, 1]) torch.Size([512, 3])
torch.Size([576, 1]) torch.Size([576, 1]) torch.Size([576, 1]) torch.Size([0, 1]) torch.Size([0, 1]) torch.Size([0, 1]) torch.Size([0, 1]) torch.Size([576, 3])
torch.Size([576, 1]) torch.Size([576, 1]) torch.Size([576, 1]) torch.Size([0, 1]) torch.Size([0, 1]) torch.Size([0, 1]) torch.Size([0, 1]) torch.Size([576, 3])
torch.Size([512, 1]) torch.Size([512, 1]) torch.Size([512, 1]) torch.Size([0, 1]) torch.Size([0, 1]) torch.Size([0, 1]) torch.Size([0, 1]) torch.Size([512, 3])
Process Process-1:1:
Traceback (most recent call last):
  File "C:\Users\10614\Anaconda3\envs\TF2.1\lib\multiprocessing\process.py", line 297, in _bootstrap
    self.run()
  File "C:\Users\10614\Anaconda3\envs\TF2.1\lib\multiprocessing\process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\10614\Desktop\FBPINNs-main\fbpinns\trainersBase.py", line 111, in train_models_multiprocess
    run.train()
  File "C:\Users\10614\Desktop\FBPINNs-main\fbpinns\main.py", line 267, in train
    xs, yjs, yjs_sum, loss = self._train_step(models, optimizers, c, D, i)
  File "C:\Users\10614\Desktop\FBPINNs-main\fbpinns\main.py", line 185, in _train_step
    yj = c.P.boundary_condition(x, *yj, *c.BOUNDARY_N)# problem-specific
TypeError: boundary_condition() missing 1 required keyword-only argument: 'args'
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Users\10614\Anaconda3\envs\TF2.1\lib\multiprocessing\connection.py", line 302, in _recv_bytes
    overlapped=True)
BrokenPipeError: [WinError 109] 管道已结束。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\10614\Anaconda3\envs\TF2.1\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
  File "C:\Users\10614\Anaconda3\envs\TF2.1\lib\site-packages\tensorboardX\event_file_writer.py", line 202, in run
    data = self._queue.get(True, queue_wait_duration)
  File "C:\Users\10614\Anaconda3\envs\TF2.1\lib\multiprocessing\queues.py", line 108, in get
    res = self._recv_bytes()
  File "C:\Users\10614\Anaconda3\envs\TF2.1\lib\multiprocessing\connection.py", line 216, in recv_bytes
    buf = self._recv_bytes(maxlength)
  File "C:\Users\10614\Anaconda3\envs\TF2.1\lib\multiprocessing\connection.py", line 321, in _recv_bytes
    raise EOFError
EOFError

**Comment by benmoseley** [comment]
Hi @135355, please check out the latest FBPINN release - it is a major update and adding soft losses is easy to do now (https://github.com/benmoseley/FBPINNs/blob/main/examples/1.%20Defining%20your%20own%20problem%20-%201D%20harmonic%20oscillator.ipynb)
